name: Hello-Francois
on : workflow_dispatch

env:
  NAME: Francois

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Dit bonjour"
        if: ${{env.NAME != 'Francois'}}
        run: echo "Salut toi ! Tu n'est pas François,! Oo"
      - name: "Coucou François"
        if: ${{env.NAME == 'Francois'}}
        run: echo "Salut $NAME ! Tu as l'air en forme !"
