name: Upload Artifact

on: workflow_dispatch

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
        # Création du fichier
      - name: create file
        run: echo "coucou" > artifact.txt
        # Upload du fichier
      - name: uplaod artifact
        # On utilise l'action github qui permet de faire l'upload
        uses: actions/upload-artifact@v3
        # on lui passe en paramètre le nom et le chemin du fichier à uploader
        with:
          name: artifact
          path: artifact.txt

  download:
    needs: upload
    name: download
    runs-on: ubuntu-latest
    steps:
      - name: download file
      # On récupère le fuichier viea l'action download-artifact
        uses: actions/download-artifact@v3
        with:
        # on lui précise le nom de l'artéfact à récupérer, sinon
        # par défaut ce sera "artifact"
          name: artifact
      - name: read-file
        # Commande Linux pour lire le contenu d'un fichier
        run: cat artifact.txt