name: "Workflow Suivant"

on:
  workflow_run:
    workflows: [Merge PR]
    types: [completed]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: "Validation"
        run: echo "Workflow exécuté"