name: Upload Artifact

on: workflow_dispatch

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
        # Création du fichier
      - name: create file
        run: echo "coucou" > artifact.txt
        # Upload du fichier
      - name: uplaod artifact
        # On utilise l'action github qui permet de faire l'upload
        uses: actions/upload-artifact@v3
        # on lui passe en paramètre le nom et le chemin du fichier à uploader
        with:
          name: artifact
          path: artifact.txt